[package]
name = "worsier-benchmark"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
worsier-formatter = { path = "../../crates/formatter", features = ["benchmarking"] }

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "formatter"
harness = false

[lints]
workspace = true
