[package]
name = "worsier-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
worsier-formatter = { path = "../crates/formatter" }

[[bin]]
name = "formatter"
path = "fuzz_targets/formatter.rs"
test = false
doc = false
bench = false
